### ISSUE TITLE
Document how to configure the Keycloak server and oauth proxy

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.sparql#32]
Please update the readme to incorporate also the oauth and keycloak configuration. 

Belongs to #36

**Comment by jcte02** [comment]
@Piiit I'll document the configuration

**Comment by Piiit** [comment]
Perfect, thx... waiting for a PR then

**Comment by Piiit** [comment]
@jcte02 Please move this issue to "In Progress" when you start to work and "To Review" when you are done...

**Comment by Piiit** [comment]
@jcte02 Please also accept the invitation to this repository: https://github.com/noi-techpark/it.bz.opendatahub.sparql/invitations

**Comment by jcte02** [comment]
@Piiit how do I move the issue to "In progress"?

**Comment by Piiit** [comment]
On the Kanban https://github.com/orgs/noi-techpark/projects/19... do you have access?

**Comment by jcte02** [comment]
No I don't have access

**Comment by Piiit** [comment]
Now?

**Comment by jcte02** [comment]
Yes

**Comment by Piiit** [comment]
@jcte02 Hi, it does not work as you describe it. Maybe we miss here some parts?

I get `403 Permission Denied: invalid_request`... Do we need Role Mappings for a user? How do I say that only some users can login? 

Could you please provide a full description similar as in https://github.com/noi-techpark/authentication-server/blob/master/docs/applications.md?

Since we do not know if left-out fields in the Keycloak configuration will be the default in future versions.

Thx

**Comment by Piiit** [comment]
We use Keycloak v12

**Comment by jcte02** [comment]
@Piiit I used your `authentication-server` repository to test the authentication before sending the PR. What I wrote in the documentation was all the steps I did on my local Keycloak instance. We clearly have a configuration mismatch here, ie you have configured something in you Keycloak instance I don't know about.
At the moment the authentication is only done on email domain, there is no granularity. If you don't expose or have the email field this can explain the failed authentication. The good news is that everything else is now working, because we are completing the flow with the callback, even if the authentication fails.
Since you mentioned wanting to manage users I would advise switching to group validation. On you Keycloak instance you can have a specific group (eg restricted) whose users will be able to access the restricted endpoint. Managing access then becomes managing that group's membership.
It would help greatly if you could provide me access to a throwaway realm on your testing auth server, or at least provide the relevant configuration, because this is an integration problem and my local configuration always worked.
To save time I will preentivly start working on the group membership. If you can't provide any details about you authentication server I can understand that but I fear it will complicate debugging. If you have access to the logs generated by the authentication proxy it would help greatly.
Regarding documentation, I will rewrite it to include screeshots of the configuration.

**Comment by Piiit** [comment]
@jcte02 Hi, we have many users on our auth server, we cannot allow all of them to access the data, even if they have the same domain... Let's have a pair programming session, then with shared screens I think we can sort the issues out easily.

**Comment by Piiit** [comment]
@jcte02 Documentation is well done, thank you
